# Generated by Django 4.2.4 on 2023-08-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=150, verbose_name='периодичность')),
                ('description', models.TextField(verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'период',
                'verbose_name_plural': 'периоды',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='тема письма')),
                ('content', models.TextField(verbose_name='тело письма')),
                ('sending_time', models.TimeField(default='12:00', verbose_name='время рассылки')),
                ('status', models.CharField(default='создана', max_length=150, verbose_name='тема письма')),
                ('sending_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.period', verbose_name='период')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
    ]
