# Generated by Django 4.2.4 on 2023-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(default='создана', max_length=150, verbose_name='статус рассылки'),
        ),
    ]
