# Generated by Django 4.2.4 on 2023-08-17 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='начало рассылки'),
        ),
    ]
