# Generated by Django 4.2.4 on 2023-08-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mail_end_date_mail_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='окончание рассылки'),
        ),
    ]
