# Generated by Django 4.2.4 on 2023-08-20 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='текст ошибки'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='mail_content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='текст сообщения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logfile',
            name='mail_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='тема письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logfile',
            name='send_from',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='от кого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logfile',
            name='send_to',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='кому'),
            preserve_default=False,
        ),
    ]
