# Generated by Django 4.2.4 on 2023-09-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_mail_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_going',
            field=models.BooleanField(default=True, verbose_name='идет на текущий момент'),
        ),
    ]
