# Generated by Django 4.2.4 on 2023-08-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
    ]
