# Generated by Django 4.2.4 on 2023-09-03 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='название')),
                ('content', models.TextField(verbose_name='содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='изображение')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
